### ISSUE TITLE
License

### ISSUE THREAD

**Issue by xtexx** [DrEvery/SCP--Disturbance#19]
**What is the license for this mod?**

Recently, I am working on another similar mod about SCP, but I found that CC-BY-SA-3.0 seems to be not compatibility with LGPL.

According to [Modrinth licensing guide](https://blog.modrinth.com/licensing-guide/), GPL is not good for Minecraft.

**Comment by DrEvery** [comment]
It's CC-BY-SA.  It has to be or we'd be in trouble.

**Comment by xtexx** [comment]
> It's CC-BY-SA. It has to be or we'd be in trouble.

But CC-BY-SA is not discouraged for code?

**Comment by DrEvery** [comment]
What do you mean?

**Comment by xtexx** [comment]
What is the license for this mod will you use?

**Comment by DrEvery** [comment]
Creative Commons By Share Alike 3.0 a.k.a CC-BY-SA 3.0, we have to because it's the SCP license and all creative works based around SCP have to use that.
